trigger:
- main

variables:
  AUTHSERVICE_MYSQL_HOST: localhost
  AUTHSERVICE_MYSQL_USER: root
  AUTHSERVICE_MYSQL_PASS: imad

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerRegistry'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'
    
- task: Maven@3
  inputs:
    mavenPomFile: 'authservice/pom.xml'
    goals: 'clean install sonar:sonar'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    repository: 'imadelfetouh99/authservice'
    command: 'buildAndPush'
    Dockerfile: 'authservice/Dockerfile'
    buildContext: 
    tags: 'latest'

