version: '3.3'
services:
  authservice-mysql:
    image: mysql
    container_name: mysql_service
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: imad

  nginx-service:
    image: nginx
    restart: always
    ports:
      - "80:80"