apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          imagePullPolicy: Always
          image: imadelfetouh99/authservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: AUTHSERVICE_MYSQL_HOST
              value: mysql-authservice-service
            - name: AUTHSERVICE_MYSQL_USER
              value: root
            - name: AUTHSERVICE_MYSQL_PASS
              value: imad
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-service
spec:
  selector:
    app: authservice
  ports:
    - port: 8080
      targetPort: 8080