apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          imagePullPolicy: Always
          image: imadelfetouh99/authservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: AUTHSERVICE_MYSQL_MASTER_HOST
              value: mysql-authservice-master-service
            - name: AUTHSERVICE_MYSQL_REPLICA_HOST
              value: mysql-authservice-replica-service
            - name: AUTHSERVICE_MYSQL_MASTER_PORT
              value: '3309'
            - name: AUTHSERVICE_MYSQL_REPLICA_PORT
              value: '3311'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: imad
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-service
spec:
  selector:
    app: authservice
  loadBalancerIP: 52.165.44.55
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080