apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          imagePullPolicy: Always
          image: imadelfetouh99/authservice
          ports:
            - containerPort: 8080
          env:
            - name: test
              value: imadd
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-service
spec:
  selector:
    app: authservice
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080