apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3.8-management
          ports:
            - name: default-port
              containerPort: 5672
            - name: web-port
              containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-extrnal-service
spec:
  selector:
    app: rabbit
  type: LoadBalancer
  ports:
    - name: web-port
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-internal-service
spec:
  selector:
    app: rabbit
  ports:
    - name: default-port
      port: 5672
      targetPort: 5672